<?php

$role = (string) ($msg['author_role'] ?? 'requester');
$kind = (string) ($msg['kind'] ?? 'message');
$isAi = $role === 'ai';

$kindLabel = match ($kind) {
    'suggestion'  => 'Suggested fix',
    'acknowledge' => 'Logged & routed',
    'handoff'     => 'Needs a person',
    default       => '',
};
?>
<div class="msg role-<?= esc($role) ?> kind-<?= esc($kind) ?>" data-message-id="<?= (int) ($msg['id'] ?? 0) ?>">
    <div class="msg-avatar" aria-hidden="true">
        <?= $isAi ? icon('sparkle', 18) : esc(strtoupper(substr((string) ($msg['author_name'] ?? '?'), 0, 1))) ?>
    </div>
    <div class="msg-body">
        <div class="msg-meta">
            <span class="msg-author"><?= esc($msg['author_name'] ?? '') ?></span>

            <?php if ($isAi): ?>
                <span class="badge-ai" title="Written by the assistant, not a person"><?= icon('sparkle', 11) ?> AI</span>
                <?php if ($kindLabel !== ''): ?>
                    <span class="badge-kind badge-kind-<?= esc($kind) ?>"><?= esc($kindLabel) ?></span>
                <?php endif ?>
            <?php else: ?>
                <span class="badge-outline"><?= esc($role) ?></span>
            <?php endif ?>

            <span class="msg-time"><?= esc(date('M j, g:i A', strtotime((string) ($msg['created_at'] ?? 'now')))) ?></span>
        </div>

        <?php if ((int) ($msg['is_solution'] ?? 0) === 1): ?>
            <span class="badge-solution"><?= icon('check', 11) ?> Solution</span>
        <?php endif ?>

        <div class="msg-text"><?= esc($msg['body'] ?? '') ?></div>

        <?php if ($isAi && $kind === 'suggestion'): ?>
            <div class="msg-foot">
                Generated by AI from your description — try it if it looks right. Either way the ticket
                stays open with the assigned team until you say it's sorted.
            </div>
        <?php elseif ($isAi && $kind === 'acknowledge'): ?>
            <div class="msg-foot">
                Filed and tagged automatically. No action is expected from you — the assigned team takes it from here.
            </div>
        <?php endif ?>
    </div>
</div>
